ALTER TABLE PEN_REQUEST_BATCH
    DROP COLUMN TSW_ACCOUNT CASCADE CONSTRAINTS;

ALTER TABLE PEN_REQUEST_BATCH
    ADD (
        CREATE_USER VARCHAR2(32) default 'PEN_REQUEST_BATCH_API' NOT NULL ,
        CREATE_DATE DATE default SYSDATE NOT NULL ,
        UPDATE_USER VARCHAR2(32) default 'PEN_REQUEST_BATCH_API' NOT NULL ,
        UPDATE_DATE DATE default SYSDATE NOT NULL
        );

ALTER TABLE PEN_REQUEST_BATCH_STUDENT
    ADD (
        CREATE_USER VARCHAR2(32) default 'PEN_REQUEST_BATCH_API' NOT NULL ,
        CREATE_DATE DATE default SYSDATE NOT NULL ,
        UPDATE_USER VARCHAR2(32) default 'PEN_REQUEST_BATCH_API' NOT NULL ,
        UPDATE_DATE DATE default SYSDATE NOT NULL
        );