CREATE TABLE PEN_REQUEST_BATCH
(
    PEN_REQUEST_BATCH_ID            RAW(16)       NOT NULL,
    SUBMISSION_NO                   VARCHAR2(8)   NOT NULL,
    PEN_REQUEST_BATCH_STATUS_CODE   VARCHAR2(10)  NOT NULL,
    PEN_REQUEST_BATCH_STATUS_REASON VARCHAR2(255),
    PEN_REQUEST_BATCH_TYPE_CODE     VARCHAR2(10)  NOT NULL,
    UNARCHIVED_FLAG                 CHAR(1)       NOT NULL,
    UNARCHIVED_BATCH_CHANGED_FLAG   CHAR(1)       NOT NULL,
    FILE_NAME                       VARCHAR2(255) NOT NULL,
    FILE_TYPE                       VARCHAR2(4)   NOT NULL,
    INSERT_DATE                     DATE          NOT NULL,
    EXTRACT_DATE                    DATE          NOT NULL,
    PROCESS_DATE                    DATE,
    SOURCE_APPLICATION              VARCHAR2(6)   NOT NULL,
    PEN_REQUEST_BATCH_SOURCE_CODE   VARCHAR2(10)  NOT NULL,
    TSW_ACCOUNT                     VARCHAR2(8)   NOT NULL,
    MINCODE                         VARCHAR2(8),
    SCHOOL_NAME                     VARCHAR2(255),
    CONTACT_NAME                    VARCHAR2(255),
    EMAIL                           VARCHAR2(255),
    OFFICE_NUMBER                   NUMBER,
    SOURCE_STUDENT_COUNT            NUMBER,
    STUDENT_COUNT                   NUMBER,
    SIS_VENDOR_NAME                 VARCHAR2(100),
    SIS_PRODUCT_NAME                VARCHAR2(100),
    SIS_PRODUCT_ID                  VARCHAR2(15),
    MATCHED_COUNT                   NUMBER,
    ISSUED_PEN_COUNT                NUMBER,
    ERROR_COUNT                     NUMBER,
    REPEAT_COUNT                    NUMBER,
    FIXABLE_COUNT                   NUMBER,
    CONSTRAINT PEN_REQUEST_BATCH_PK PRIMARY KEY (PEN_REQUEST_BATCH_ID)
);
COMMENT ON TABLE PEN_REQUEST_BATCH IS 'Contains meta data about the overall batch, such as the submission number, the school Mincode, the file name and type, etc.';

-- Column Comments
COMMENT ON COLUMN PEN_REQUEST_BATCH.PEN_REQUEST_BATCH_ID IS 'Unique surrogate key for each PEN Request Batch. GUID value must be provided during insert.';
COMMENT ON COLUMN PEN_REQUEST_BATCH.SUBMISSION_NO IS 'Unique natural identifier for each PEN Request Batch. At present (2020), these are generated by TSW as these files are added to the TSW.PEN_WEB_BLOBS table.';
COMMENT ON COLUMN PEN_REQUEST_BATCH.PEN_REQUEST_BATCH_STATUS_CODE IS 'A code identifying the current status of the batch.';
COMMENT ON COLUMN PEN_REQUEST_BATCH.PEN_REQUEST_BATCH_STATUS_REASON IS 'Reason for the current batch status. Only specified during exceptional circumstances.';
COMMENT ON COLUMN PEN_REQUEST_BATCH.UNARCHIVED_FLAG IS 'A boolean flag indicating if the batch has been unarchived, or not. Values Y or N. Default N.';
COMMENT ON COLUMN PEN_REQUEST_BATCH.UNARCHIVED_BATCH_CHANGED_FLAG IS 'A boolean flag indicating if an unarchived batch has been changed, or not. Values Y or N. This is a "dirty bit" for an unarchived batch. Default N.';
COMMENT ON COLUMN PEN_REQUEST_BATCH.FILE_NAME IS 'The name of the batch file uploaded by the school. Should be "<mincode>.PEN" ';
COMMENT ON COLUMN PEN_REQUEST_BATCH.FILE_TYPE IS 'The type of the file uploaded by the school.';
COMMENT ON COLUMN PEN_REQUEST_BATCH.INSERT_DATE IS 'The date and time the file landed at the Ministry of Education.';
COMMENT ON COLUMN PEN_REQUEST_BATCH.EXTRACT_DATE IS 'The date the file was extracted and loaded.';
COMMENT ON COLUMN PEN_REQUEST_BATCH.PROCESS_DATE IS 'The date the file was processed.';
COMMENT ON COLUMN PEN_REQUEST_BATCH.SOURCE_APPLICATION IS 'A short code identifying the source system at the school. This is defined by the schools and is not constrained by a code table. ';
COMMENT ON COLUMN PEN_REQUEST_BATCH.PEN_REQUEST_BATCH_SOURCE_CODE IS 'A code identifying which ministry system received the file, such as TSW PENWeb. Default "TSWPENWEB"';
COMMENT ON COLUMN PEN_REQUEST_BATCH.TSW_ACCOUNT IS 'The TSW account used to upload the batch. Should be the same as the Mincode.';
COMMENT ON COLUMN PEN_REQUEST_BATCH.MINCODE IS 'Ministry code for the school that submitted the batch.';
COMMENT ON COLUMN PEN_REQUEST_BATCH.SCHOOL_NAME IS 'Name of the school as provided in the batch file.';
COMMENT ON COLUMN PEN_REQUEST_BATCH.CONTACT_NAME IS 'Name of the contact person for the school.';
COMMENT ON COLUMN PEN_REQUEST_BATCH.EMAIL IS 'Email for the contact person.';
COMMENT ON COLUMN PEN_REQUEST_BATCH.OFFICE_NUMBER IS 'Identifies which school office submitted the request. Only use by schools with multiple offices.';
COMMENT ON COLUMN PEN_REQUEST_BATCH.SOURCE_STUDENT_COUNT IS 'The number of students contained in the batch, according to the data in the source system.';
COMMENT ON COLUMN PEN_REQUEST_BATCH.STUDENT_COUNT IS 'The number of students contained in the batch.';
COMMENT ON COLUMN PEN_REQUEST_BATCH.PEN_REQUEST_BATCH_TYPE_CODE IS ' A code identifying the type the batch: Normal School batch, Nominal Roll batch, SLD Validation batch.';
COMMENT ON COLUMN PEN_REQUEST_BATCH.SIS_VENDOR_NAME IS 'The name of the vendor of the Student information System (SIS) used by the submitting school. E.g. Follett';
COMMENT ON COLUMN PEN_REQUEST_BATCH.SIS_PRODUCT_NAME IS 'The name of the Student information System (SIS) product used by the submitting school. E.g. Aspen';
COMMENT ON COLUMN PEN_REQUEST_BATCH.SIS_PRODUCT_ID IS 'The ID of the Student information System (SIS) product used by the submitting school. E.g. A version number.';
COMMENT ON COLUMN PEN_REQUEST_BATCH.MATCHED_COUNT IS 'A dynamic, running count of the number of PEN request records in the batch that have been matched to existing records in the Student table.';
COMMENT ON COLUMN PEN_REQUEST_BATCH.ISSUED_PEN_COUNT IS 'A dynamic, running count of the number of PEN request records in the batch that resulted in the creation of a new Student/PEN in the Student table.';
COMMENT ON COLUMN PEN_REQUEST_BATCH.ERROR_COUNT IS 'A dynamic, running count of the number of PEN request records in the batch that have errors of some sort (PEN not yet matched nor issued). Includes Validation errors, Repeats and Fixables.';
COMMENT ON COLUMN PEN_REQUEST_BATCH.REPEAT_COUNT IS 'A dynamic, running count of the number of PEN request records in the batch that are a repeat of an earlier PEN request by the same school, using the same request data.';
COMMENT ON COLUMN PEN_REQUEST_BATCH.FIXABLE_COUNT IS 'A dynamic, running count of the number of PEN request records in the batch that are valid requests but could not automatically be fulfilled, and require manual review.';

CREATE TABLE PEN_REQUEST_BATCH_STUDENT
(
    PEN_REQUEST_BATCH_STUDENT_ID          RAW(16)      NOT NULL,
    PEN_REQUEST_BATCH_ID                  RAW(16)      NOT NULL,
    PEN_REQUEST_BATCH_STUDENT_STATUS_CODE VARCHAR2(10) NOT NULL,
    LOCAL_ID                              VARCHAR2(12),
    SUBMITTED_PEN                         VARCHAR2(9),
    LEGAL_LAST_NAME                       VARCHAR2(255),
    LEGAL_FIRST_NAME                      VARCHAR2(255),
    LEGAL_MIDDLE_NAMES                    VARCHAR2(255),
    USUAL_LAST_NAME                       VARCHAR2(255),
    USUAL_FIRST_NAME                      VARCHAR2(255),
    USUAL_MIDDLE_NAMES                    VARCHAR2(255),
    DOB                                   VARCHAR2(8),
    GENDER_CODE                           VARCHAR2(1),
    GRADE_CODE                            VARCHAR2(2),
    POSTAL_CODE                           VARCHAR2(6),
    ASSIGNED_PEN                          VARCHAR2(9),
    STUDENT_ID                            RAW(16),
    CONSTRAINT PEN_REQUEST_BATCH_STUDENT_PK PRIMARY KEY (PEN_REQUEST_BATCH_STUDENT_ID)
);
COMMENT ON TABLE PEN_REQUEST_BATCH_STUDENT IS 'Contains the individual PEN Requests for a PEN Request Batch. Each record contains information about the student for whom the school is requesting a PEN.';

-- Column Comments
COMMENT ON COLUMN PEN_REQUEST_BATCH_STUDENT.PEN_REQUEST_BATCH_STUDENT_ID IS 'Unique surrogate key for each PEN Request Student record. GUID value must be provided during insert.';
COMMENT ON COLUMN PEN_REQUEST_BATCH_STUDENT.PEN_REQUEST_BATCH_ID IS 'Foreign key to the parent PEN Request Batch record.';
COMMENT ON COLUMN PEN_REQUEST_BATCH_STUDENT.PEN_REQUEST_BATCH_STUDENT_STATUS_CODE IS 'Code.';
COMMENT ON COLUMN PEN_REQUEST_BATCH_STUDENT.LOCAL_ID IS 'The local identifier for the student. Usually the student number.';
COMMENT ON COLUMN PEN_REQUEST_BATCH_STUDENT.SUBMITTED_PEN IS 'The pen provided in the submission, if any. Usually a pen is not provided.';
COMMENT ON COLUMN PEN_REQUEST_BATCH_STUDENT.LEGAL_LAST_NAME IS 'Student''s legal last name.';
COMMENT ON COLUMN PEN_REQUEST_BATCH_STUDENT.LEGAL_FIRST_NAME IS 'Student''s legal first name.';
COMMENT ON COLUMN PEN_REQUEST_BATCH_STUDENT.LEGAL_MIDDLE_NAMES IS 'Student''s legal middle names.';
COMMENT ON COLUMN PEN_REQUEST_BATCH_STUDENT.USUAL_LAST_NAME IS 'Student''s usual last name.';
COMMENT ON COLUMN PEN_REQUEST_BATCH_STUDENT.USUAL_FIRST_NAME IS 'Student''s usual first name.';
COMMENT ON COLUMN PEN_REQUEST_BATCH_STUDENT.USUAL_MIDDLE_NAMES IS 'Student''s usual middle names.';
COMMENT ON COLUMN PEN_REQUEST_BATCH_STUDENT.DOB IS 'Student''s date of birth.';
COMMENT ON COLUMN PEN_REQUEST_BATCH_STUDENT.GENDER_CODE IS 'Code identifying the student''s gender.';
COMMENT ON COLUMN PEN_REQUEST_BATCH_STUDENT.GRADE_CODE IS 'Code identifying the student''s grade level.';
COMMENT ON COLUMN PEN_REQUEST_BATCH_STUDENT.POSTAL_CODE IS 'Student''s postal code.';
COMMENT ON COLUMN PEN_REQUEST_BATCH_STUDENT.ASSIGNED_PEN IS 'The PEN assigned to this PEN request.';
COMMENT ON COLUMN PEN_REQUEST_BATCH_STUDENT.STUDENT_ID IS 'Foreign key to the matching the student record, once the Student/PEN record has been matched or created.';

ALTER TABLE PEN_REQUEST_BATCH_STUDENT
    ADD CONSTRAINT PEN_REQUEST_BATCH_STUDENT_PEN_REQUEST_BATCH_ID_FK FOREIGN KEY (PEN_REQUEST_BATCH_ID) REFERENCES PEN_REQUEST_BATCH (PEN_REQUEST_BATCH_ID);

CREATE TABLE PEN_REQUEST_BATCH_STATUS_CODE
(
    PEN_REQUEST_BATCH_STATUS_CODE VARCHAR2(10)           NOT NULL,
    LABEL                         VARCHAR2(30),
    DESCRIPTION                   VARCHAR2(255),
    DISPLAY_ORDER                 NUMBER DEFAULT 1       NOT NULL,
    EFFECTIVE_DATE                DATE                   NOT NULL,
    EXPIRY_DATE                   DATE                   NOT NULL,
    CREATE_USER                   VARCHAR2(32)           NOT NULL,
    CREATE_DATE                   DATE   DEFAULT SYSDATE NOT NULL,
    UPDATE_USER                   VARCHAR2(32)           NOT NULL,
    UPDATE_DATE                   DATE   DEFAULT SYSDATE NOT NULL,
    CONSTRAINT PEN_REQUEST_BATCH_STATUS_CODE_PK PRIMARY KEY (PEN_REQUEST_BATCH_STATUS_CODE)
);
COMMENT ON TABLE PEN_REQUEST_BATCH_STATUS_CODE IS 'Lists the possible status values for PEN request batches.';

ALTER TABLE PEN_REQUEST_BATCH
    ADD CONSTRAINT PEN_REQUEST_BATCH_PEN_REQUEST_BATCH_STATUS_CODE_FK FOREIGN KEY (PEN_REQUEST_BATCH_STATUS_CODE) REFERENCES PEN_REQUEST_BATCH_STATUS_CODE (PEN_REQUEST_BATCH_STATUS_CODE);

CREATE TABLE PEN_REQUEST_BATCH_SOURCE_CODE
(
    PEN_REQUEST_BATCH_SOURCE_CODE VARCHAR2(10)           NOT NULL,
    LABEL                         VARCHAR2(30),
    DESCRIPTION                   VARCHAR2(255),
    DISPLAY_ORDER                 NUMBER DEFAULT 1       NOT NULL,
    EFFECTIVE_DATE                DATE                   NOT NULL,
    EXPIRY_DATE                   DATE                   NOT NULL,
    CREATE_USER                   VARCHAR2(32)           NOT NULL,
    CREATE_DATE                   DATE   DEFAULT SYSDATE NOT NULL,
    UPDATE_USER                   VARCHAR2(32)           NOT NULL,
    UPDATE_DATE                   DATE   DEFAULT SYSDATE NOT NULL,
    CONSTRAINT PEN_REQUEST_BATCH_SOURCE_CODE_PK PRIMARY KEY (PEN_REQUEST_BATCH_SOURCE_CODE)
);
COMMENT ON TABLE PEN_REQUEST_BATCH_SOURCE_CODE IS 'Lists the ministry system that handle PEN Request Batch files, such as TSW PENWeb.';

ALTER TABLE PEN_REQUEST_BATCH
    ADD CONSTRAINT PEN_REQUEST_BATCH_PEN_REQUEST_BATCH_SOURCE_CODE_FK FOREIGN KEY (PEN_REQUEST_BATCH_SOURCE_CODE) REFERENCES PEN_REQUEST_BATCH_SOURCE_CODE (PEN_REQUEST_BATCH_SOURCE_CODE);

CREATE TABLE PEN_REQUEST_BATCH_TYPE_CODE
(
    PEN_REQUEST_BATCH_TYPE_CODE VARCHAR2(10)           NOT NULL,
    LABEL                       VARCHAR2(30),
    DESCRIPTION                 VARCHAR2(255),
    DISPLAY_ORDER               NUMBER DEFAULT 1       NOT NULL,
    EFFECTIVE_DATE              DATE                   NOT NULL,
    EXPIRY_DATE                 DATE                   NOT NULL,
    CREATE_USER                 VARCHAR2(32)           NOT NULL,
    CREATE_DATE                 DATE   DEFAULT SYSDATE NOT NULL,
    UPDATE_USER                 VARCHAR2(32)           NOT NULL,
    UPDATE_DATE                 DATE   DEFAULT SYSDATE NOT NULL,
    CONSTRAINT PEN_REQUEST_BATCH_TYPE_CODE_PK PRIMARY KEY (PEN_REQUEST_BATCH_TYPE_CODE)
);
COMMENT ON TABLE PEN_REQUEST_BATCH_TYPE_CODE IS 'Lists the possible type values for PEN request batches.';

ALTER TABLE PEN_REQUEST_BATCH
    ADD CONSTRAINT PEN_REQUEST_BATCH_PEN_REQUEST_BATCH_TYPE_CODE_FK FOREIGN KEY (PEN_REQUEST_BATCH_TYPE_CODE) REFERENCES PEN_REQUEST_BATCH_TYPE_CODE (PEN_REQUEST_BATCH_TYPE_CODE);

CREATE TABLE PEN_REQUEST_BATCH_STUDENT_STATUS_CODE
(
    PEN_REQUEST_BATCH_STUDENT_STATUS_CODE VARCHAR2(10)           NOT NULL,
    LABEL                                 VARCHAR2(30),
    DESCRIPTION                           VARCHAR2(255),
    DISPLAY_ORDER                         NUMBER DEFAULT 1       NOT NULL,
    EFFECTIVE_DATE                        DATE                   NOT NULL,
    EXPIRY_DATE                           DATE                   NOT NULL,
    CREATE_USER                           VARCHAR2(32)           NOT NULL,
    CREATE_DATE                           DATE   DEFAULT SYSDATE NOT NULL,
    UPDATE_USER                           VARCHAR2(32)           NOT NULL,
    UPDATE_DATE                           DATE   DEFAULT SYSDATE NOT NULL,
    CONSTRAINT PEN_REQUEST_BATCH_STUDENT_STATUS_CODE_PK PRIMARY KEY (PEN_REQUEST_BATCH_STUDENT_STATUS_CODE)
);
COMMENT ON TABLE PEN_REQUEST_BATCH_STUDENT_STATUS_CODE IS 'Student Status Code lists the possible statuses for student records. They are A=Active, D=Deceased, M=Merged (to another PEN), and X=Deleted.';

ALTER TABLE PEN_REQUEST_BATCH_STUDENT
    ADD CONSTRAINT PEN_REQUEST_BATCH_STUDENT_PEN_REQUEST_BATCH_STUDENT_STATUS_CODE_FK FOREIGN KEY (PEN_REQUEST_BATCH_STUDENT_STATUS_CODE) REFERENCES PEN_REQUEST_BATCH_STUDENT_STATUS_CODE (PEN_REQUEST_BATCH_STUDENT_STATUS_CODE);

CREATE TABLE PEN_REQUEST_BATCH_SHEDLOCK
(
    NAME       VARCHAR(64),
    LOCK_UNTIL TIMESTAMP(3) NULL,
    LOCKED_AT  TIMESTAMP(3) NULL,
    LOCKED_BY  VARCHAR(255),
    CONSTRAINT PEN_REQUEST_BATCH_SHEDLOCK_PK PRIMARY KEY (NAME)
);
COMMENT ON TABLE PEN_REQUEST_BATCH_SHEDLOCK IS 'This table is used to achieve distributed lock between pods, for schedulers.';

--PEN Request Batch Type Codes
INSERT INTO PEN_REQUEST_BATCH_TYPE_CODE (PEN_REQUEST_BATCH_TYPE_CODE, LABEL, DESCRIPTION, DISPLAY_ORDER, EFFECTIVE_DATE,
                                         EXPIRY_DATE, CREATE_USER, CREATE_DATE, UPDATE_USER, UPDATE_DATE)
VALUES ('SCHOOL',
        'School PEN Request Batch',
        'Normal PEN Request batch from a school (early learning through PSI).',
        1,
        to_date('2020-01-01', 'YYYY-MM-DD'),
        to_date('2099-12-31', 'YYYY-MM-DD'),
        'IDIR/MVILLENE',
        to_date('2019-11-07', 'YYYY-MM-DD'),
        'IDIR/MVILLENE',
        to_date('2019-11-07', 'YYYY-MM-DD'));

INSERT INTO PEN_REQUEST_BATCH_TYPE_CODE (PEN_REQUEST_BATCH_TYPE_CODE, LABEL, DESCRIPTION, DISPLAY_ORDER, EFFECTIVE_DATE,
                                         EXPIRY_DATE, CREATE_USER, CREATE_DATE, UPDATE_USER, UPDATE_DATE)
VALUES ('NOMROLL',
        'Nominal Roll Batch',
        'A PEN Request/Match batch generated as part of the Nominal Roll funding reconciliation process.',
        2,
        to_date('2020-01-01', 'YYYY-MM-DD'),
        to_date('2099-12-31', 'YYYY-MM-DD'),
        'IDIR/MVILLENE',
        to_date('2019-11-07', 'YYYY-MM-DD'),
        'IDIR/MVILLENE',
        to_date('2019-11-07', 'YYYY-MM-DD'));

INSERT INTO PEN_REQUEST_BATCH_TYPE_CODE (PEN_REQUEST_BATCH_TYPE_CODE, LABEL, DESCRIPTION, DISPLAY_ORDER, EFFECTIVE_DATE,
                                         EXPIRY_DATE, CREATE_USER, CREATE_DATE, UPDATE_USER, UPDATE_DATE)
VALUES ('SLD',
        'SLD Data Batch',
        'A PEN Request batch used for validation by schools of their School Level Data (SLD) before submission of the data.',
        3,
        to_date('2020-01-01', 'YYYY-MM-DD'),
        to_date('2099-12-31', 'YYYY-MM-DD'),
        'IDIR/MVILLENE',
        to_date('2019-11-07', 'YYYY-MM-DD'),
        'IDIR/MVILLENE',
        to_date('2019-11-07', 'YYYY-MM-DD'));

--PEN Request Batch Status Codes
INSERT INTO PEN_REQUEST_BATCH_STUDENT_STATUS_CODE (PEN_REQUEST_BATCH_STUDENT_STATUS_CODE, LABEL, DESCRIPTION,
                                                   DISPLAY_ORDER, EFFECTIVE_DATE, EXPIRY_DATE, CREATE_USER, CREATE_DATE,
                                                   UPDATE_USER, UPDATE_DATE)
VALUES ('NEW',
        'New - Load in progress',
        'New - Load in progress',
        1,
        to_date('2020-01-01', 'YYYY-MM-DD'),
        to_date('2099-12-31', 'YYYY-MM-DD'),
        'IDIR/MVILLENE',
        to_date('2019-11-07', 'YYYY-MM-DD'),
        'IDIR/MVILLENE',
        to_date('2019-11-07', 'YYYY-MM-DD'));

INSERT INTO PEN_REQUEST_BATCH_STUDENT_STATUS_CODE (PEN_REQUEST_BATCH_STUDENT_STATUS_CODE, LABEL, DESCRIPTION,
                                                   DISPLAY_ORDER, EFFECTIVE_DATE, EXPIRY_DATE, CREATE_USER, CREATE_DATE,
                                                   UPDATE_USER, UPDATE_DATE)
VALUES ('LOADED',
        'Batch loaded to database',
        'Batch loaded to database',
        2,
        to_date('2020-01-01', 'YYYY-MM-DD'),
        to_date('2099-12-31', 'YYYY-MM-DD'),
        'IDIR/MVILLENE',
        to_date('2019-11-07', 'YYYY-MM-DD'),
        'IDIR/MVILLENE',
        to_date('2019-11-07', 'YYYY-MM-DD'));

INSERT INTO PEN_REQUEST_BATCH_STUDENT_STATUS_CODE (PEN_REQUEST_BATCH_STUDENT_STATUS_CODE, LABEL, DESCRIPTION,
                                                   DISPLAY_ORDER, EFFECTIVE_DATE, EXPIRY_DATE, CREATE_USER, CREATE_DATE,
                                                   UPDATE_USER, UPDATE_DATE)
VALUES ('VALIDATED',
        'Batch validated in database',
        'Batch validated in database and ready for auto-match',
        3,
        to_date('2020-01-01', 'YYYY-MM-DD'),
        to_date('2099-12-31', 'YYYY-MM-DD'),
        'IDIR/MVILLENE',
        to_date('2019-11-07', 'YYYY-MM-DD'),
        'IDIR/MVILLENE',
        to_date('2019-11-07', 'YYYY-MM-DD'));

INSERT INTO PEN_REQUEST_BATCH_STUDENT_STATUS_CODE (PEN_REQUEST_BATCH_STUDENT_STATUS_CODE, LABEL, DESCRIPTION,
                                                   DISPLAY_ORDER, EFFECTIVE_DATE, EXPIRY_DATE, CREATE_USER, CREATE_DATE,
                                                   UPDATE_USER, UPDATE_DATE)
VALUES ('ACTIVE',
        'Batch active for staff review',
        'Batch has been auto-matched and is in manual review',
        4,
        to_date('2020-01-01', 'YYYY-MM-DD'),
        to_date('2099-12-31', 'YYYY-MM-DD'),
        'IDIR/MVILLENE',
        to_date('2019-11-07', 'YYYY-MM-DD'),
        'IDIR/MVILLENE',
        to_date('2019-11-07', 'YYYY-MM-DD'));

INSERT INTO PEN_REQUEST_BATCH_STUDENT_STATUS_CODE (PEN_REQUEST_BATCH_STUDENT_STATUS_CODE, LABEL, DESCRIPTION,
                                                   DISPLAY_ORDER, EFFECTIVE_DATE, EXPIRY_DATE, CREATE_USER, CREATE_DATE,
                                                   UPDATE_USER, UPDATE_DATE)
VALUES ('ARCHIVED',
        'Batch completed and archived',
        'Batch has been completed and archived and response files provided to the school',
        5,
        to_date('2020-01-01', 'YYYY-MM-DD'),
        to_date('2099-12-31', 'YYYY-MM-DD'),
        'IDIR/MVILLENE',
        to_date('2019-11-07', 'YYYY-MM-DD'),
        'IDIR/MVILLENE',
        to_date('2019-11-07', 'YYYY-MM-DD'));

INSERT INTO PEN_REQUEST_BATCH_STUDENT_STATUS_CODE (PEN_REQUEST_BATCH_STUDENT_STATUS_CODE, LABEL, DESCRIPTION,
                                                   DISPLAY_ORDER, EFFECTIVE_DATE, EXPIRY_DATE, CREATE_USER, CREATE_DATE,
                                                   UPDATE_USER, UPDATE_DATE)
VALUES ('UNARCHIVED',
        'Batch has been unarchived',
        'Batch has been unarchived for further manual review',
        6,
        to_date('2020-01-01', 'YYYY-MM-DD'),
        to_date('2099-12-31', 'YYYY-MM-DD'),
        'IDIR/MVILLENE',
        to_date('2019-11-07', 'YYYY-MM-DD'),
        'IDIR/MVILLENE',
        to_date('2019-11-07', 'YYYY-MM-DD'));

INSERT INTO PEN_REQUEST_BATCH_STUDENT_STATUS_CODE (PEN_REQUEST_BATCH_STUDENT_STATUS_CODE, LABEL, DESCRIPTION,
                                                   DISPLAY_ORDER, EFFECTIVE_DATE, EXPIRY_DATE, CREATE_USER, CREATE_DATE,
                                                   UPDATE_USER, UPDATE_DATE)
VALUES ('LOADFAIL',
        'Batch failed loading',
        'Batch could not be loaded into the database',
        7,
        to_date('2020-01-01', 'YYYY-MM-DD'),
        to_date('2099-12-31', 'YYYY-MM-DD'),
        'IDIR/MVILLENE',
        to_date('2019-11-07', 'YYYY-MM-DD'),
        'IDIR/MVILLENE',
        to_date('2019-11-07', 'YYYY-MM-DD'));

--PEN Request Batch Source Codes
INSERT INTO PEN_REQUEST_BATCH_SOURCE_CODE (PEN_REQUEST_BATCH_SOURCE_CODE, LABEL, DESCRIPTION, DISPLAY_ORDER,
                                           EFFECTIVE_DATE, EXPIRY_DATE, CREATE_USER, CREATE_DATE, UPDATE_USER,
                                           UPDATE_DATE)
VALUES ('TSWPENWEB',
        'TSW PENWeb',
        'The PENWeb system that is part of TSW, as of 2020',
        1,
        to_date('2020-01-01', 'YYYY-MM-DD'),
        to_date('2099-12-31', 'YYYY-MM-DD'),
        'IDIR/MVILLENE',
        to_date('2019-11-07', 'YYYY-MM-DD'),
        'IDIR/MVILLENE',
        to_date('2019-11-07', 'YYYY-MM-DD'));

--PEN Request Batch Student Status Codes
INSERT INTO PEN_REQUEST_BATCH_STUDENT_STATUS_CODE (PEN_REQUEST_BATCH_STUDENT_STATUS_CODE, LABEL, DESCRIPTION,
                                                   DISPLAY_ORDER, EFFECTIVE_DATE, EXPIRY_DATE, CREATE_USER, CREATE_DATE,
                                                   UPDATE_USER, UPDATE_DATE)
VALUES ('LOADED',
        'Loaded',
        'Request loaded to database',
        1,
        to_date('2020-01-01', 'YYYY-MM-DD'),
        to_date('2099-12-31', 'YYYY-MM-DD'),
        'IDIR/MVILLENE',
        to_date('2019-11-07', 'YYYY-MM-DD'),
        'IDIR/MVILLENE',
        to_date('2019-11-07', 'YYYY-MM-DD'));

INSERT INTO PEN_REQUEST_BATCH_STUDENT_STATUS_CODE (PEN_REQUEST_BATCH_STUDENT_STATUS_CODE, LABEL, DESCRIPTION,
                                                   DISPLAY_ORDER, EFFECTIVE_DATE, EXPIRY_DATE, CREATE_USER, CREATE_DATE,
                                                   UPDATE_USER, UPDATE_DATE)
VALUES ('ERROR',
        'Validation Error',
        'Request fails one or more validation checks',
        2,
        to_date('2020-01-01', 'YYYY-MM-DD'),
        to_date('2099-12-31', 'YYYY-MM-DD'),
        'IDIR/MVILLENE',
        to_date('2019-11-07', 'YYYY-MM-DD'),
        'IDIR/MVILLENE',
        to_date('2019-11-07', 'YYYY-MM-DD'));

INSERT INTO PEN_REQUEST_BATCH_STUDENT_STATUS_CODE (PEN_REQUEST_BATCH_STUDENT_STATUS_CODE, LABEL, DESCRIPTION,
                                                   DISPLAY_ORDER, EFFECTIVE_DATE, EXPIRY_DATE, CREATE_USER, CREATE_DATE,
                                                   UPDATE_USER, UPDATE_DATE)
VALUES ('SYSMATCHED',
        'System Matched',
        'Request matched to an existing student by the system',
        3,
        to_date('2020-01-01', 'YYYY-MM-DD'),
        to_date('2099-12-31', 'YYYY-MM-DD'),
        'IDIR/MVILLENE',
        to_date('2019-11-07', 'YYYY-MM-DD'),
        'IDIR/MVILLENE',
        to_date('2019-11-07', 'YYYY-MM-DD'));

INSERT INTO PEN_REQUEST_BATCH_STUDENT_STATUS_CODE (PEN_REQUEST_BATCH_STUDENT_STATUS_CODE, LABEL, DESCRIPTION,
                                                   DISPLAY_ORDER, EFFECTIVE_DATE, EXPIRY_DATE, CREATE_USER, CREATE_DATE,
                                                   UPDATE_USER, UPDATE_DATE)
VALUES ('SYSNEWPEN',
        'System issued new PEN',
        'Request triggered the creation of a new PEN by the system',
        4,
        to_date('2020-01-01', 'YYYY-MM-DD'),
        to_date('2099-12-31', 'YYYY-MM-DD'),
        'IDIR/MVILLENE',
        to_date('2019-11-07', 'YYYY-MM-DD'),
        'IDIR/MVILLENE',
        to_date('2019-11-07', 'YYYY-MM-DD'));

INSERT INTO PEN_REQUEST_BATCH_STUDENT_STATUS_CODE (PEN_REQUEST_BATCH_STUDENT_STATUS_CODE, LABEL, DESCRIPTION,
                                                   DISPLAY_ORDER, EFFECTIVE_DATE, EXPIRY_DATE, CREATE_USER, CREATE_DATE,
                                                   UPDATE_USER, UPDATE_DATE)
VALUES ('REPEAT',
        'Repeated request',
        'Request is the same as the last request for this student',
        5,
        to_date('2020-01-01', 'YYYY-MM-DD'),
        to_date('2099-12-31', 'YYYY-MM-DD'),
        'IDIR/MVILLENE',
        to_date('2019-11-07', 'YYYY-MM-DD'),
        'IDIR/MVILLENE',
        to_date('2019-11-07', 'YYYY-MM-DD'));

INSERT INTO PEN_REQUEST_BATCH_STUDENT_STATUS_CODE (PEN_REQUEST_BATCH_STUDENT_STATUS_CODE, LABEL, DESCRIPTION,
                                                   DISPLAY_ORDER, EFFECTIVE_DATE, EXPIRY_DATE, CREATE_USER, CREATE_DATE,
                                                   UPDATE_USER, UPDATE_DATE)
VALUES ('NEWFIXABLE',
        'New Fixable Request',
        'Request is new and need manual matching performed by a staff user',
        6,
        to_date('2020-01-01', 'YYYY-MM-DD'),
        to_date('2099-12-31', 'YYYY-MM-DD'),
        'IDIR/MVILLENE',
        to_date('2019-11-07', 'YYYY-MM-DD'),
        'IDIR/MVILLENE',
        to_date('2019-11-07', 'YYYY-MM-DD'));

INSERT INTO PEN_REQUEST_BATCH_STUDENT_STATUS_CODE (PEN_REQUEST_BATCH_STUDENT_STATUS_CODE, LABEL, DESCRIPTION,
                                                   DISPLAY_ORDER, EFFECTIVE_DATE, EXPIRY_DATE, CREATE_USER, CREATE_DATE,
                                                   UPDATE_USER, UPDATE_DATE)
VALUES ('USRMATCHED',
        'User Matched',
        'Request matched to an existing student by a staff member',
        7,
        to_date('2020-01-01', 'YYYY-MM-DD'),
        to_date('2099-12-31', 'YYYY-MM-DD'),
        'IDIR/MVILLENE',
        to_date('2019-11-07', 'YYYY-MM-DD'),
        'IDIR/MVILLENE',
        to_date('2019-11-07', 'YYYY-MM-DD'));

INSERT INTO PEN_REQUEST_BATCH_STUDENT_STATUS_CODE (PEN_REQUEST_BATCH_STUDENT_STATUS_CODE, LABEL, DESCRIPTION,
                                                   DISPLAY_ORDER, EFFECTIVE_DATE, EXPIRY_DATE, CREATE_USER, CREATE_DATE,
                                                   UPDATE_USER, UPDATE_DATE)
VALUES ('USRNEWPEN',
        'User issued new PEN',
        'Request triggered the creation of a new PEN by the user',
        8,
        to_date('2020-01-01', 'YYYY-MM-DD'),
        to_date('2099-12-31', 'YYYY-MM-DD'),
        'IDIR/MVILLENE',
        to_date('2019-11-07', 'YYYY-MM-DD'),
        'IDIR/MVILLENE',
        to_date('2019-11-07', 'YYYY-MM-DD'));

INSERT INTO PEN_REQUEST_BATCH_STUDENT_STATUS_CODE (PEN_REQUEST_BATCH_STUDENT_STATUS_CODE, LABEL, DESCRIPTION,
                                                   DISPLAY_ORDER, EFFECTIVE_DATE, EXPIRY_DATE, CREATE_USER, CREATE_DATE,
                                                   UPDATE_USER, UPDATE_DATE)
VALUES ('RETURNED',
        'User returned request',
        'Request returned to the school for additional details needed to process the request',
        9,
        to_date('2020-01-01', 'YYYY-MM-DD'),
        to_date('2099-12-31', 'YYYY-MM-DD'),
        'IDIR/MVILLENE',
        to_date('2019-11-07', 'YYYY-MM-DD'),
        'IDIR/MVILLENE',
        to_date('2019-11-07', 'YYYY-MM-DD'));
