ALTER TABLE PEN_REQUEST_BATCH
MODIFY (
           CREATE_USER VARCHAR2(100),
           UPDATE_USER VARCHAR2(100)
       );

ALTER TABLE PEN_REQUEST_BATCH_HISTORY
MODIFY (
           CREATE_USER VARCHAR2(100),
           UPDATE_USER VARCHAR2(100)
       );

ALTER TABLE PEN_REQUEST_BATCH_SAGA
MODIFY (
           CREATE_USER VARCHAR2(100),
           UPDATE_USER VARCHAR2(100)
       );

ALTER TABLE PEN_REQUEST_BATCH_SAGA_EVENT_STATES
MODIFY (
           CREATE_USER VARCHAR2(100),
           UPDATE_USER VARCHAR2(100)
       );

ALTER TABLE PEN_REQUEST_BATCH_STUDENT
MODIFY (
           CREATE_USER VARCHAR2(100),
           UPDATE_USER VARCHAR2(100)
       );
