WHENEVER SQLERROR EXIT FAILURE
--Modify PAYLOAD_BLOB Column to BLOB
ALTER TABLE PEN_REQUEST_BATCH_SAGA
    MODIFY (
        PAYLOAD_BLOB BLOB
        );
UPDATE PEN_REQUEST_BATCH_SAGA SET PAYLOAD_BLOB = UTL_RAW.CAST_TO_RAW(PAYLOAD);
ALTER TABLE PEN_REQUEST_BATCH_SAGA DROP COLUMN PAYLOAD;
ALTER TABLE PEN_REQUEST_BATCH_SAGA RENAME COLUMN PAYLOAD_BLOB TO PAYLOAD;
ALTER TABLE PEN_REQUEST_BATCH_SAGA
    MODIFY (
        PAYLOAD NOT NULL
        );

--Modify SAGA_EVENT_RESPONSE_BLOB Column to BLOB
ALTER TABLE PEN_REQUEST_BATCH_SAGA_EVENT_STATES
    MODIFY (
        SAGA_EVENT_RESPONSE_BLOB BLOB
        );
UPDATE PEN_REQUEST_BATCH_SAGA_EVENT_STATES SET SAGA_EVENT_RESPONSE_BLOB = UTL_RAW.CAST_TO_RAW(SAGA_EVENT_RESPONSE);
ALTER TABLE PEN_REQUEST_BATCH_SAGA_EVENT_STATES DROP COLUMN SAGA_EVENT_RESPONSE;
ALTER TABLE PEN_REQUEST_BATCH_SAGA_EVENT_STATES RENAME COLUMN SAGA_EVENT_RESPONSE_BLOB TO SAGA_EVENT_RESPONSE;
ALTER TABLE PEN_REQUEST_BATCH_SAGA_EVENT_STATES
    MODIFY (
        SAGA_EVENT_RESPONSE NOT NULL
        );

--Modify EVENT_PAYLOAD_BLOB Column to BLOB
ALTER TABLE PEN_REQUEST_BATCH_EVENT
    MODIFY (
        EVENT_PAYLOAD_BLOB BLOB
        );
UPDATE PEN_REQUEST_BATCH_EVENT SET EVENT_PAYLOAD_BLOB = UTL_RAW.CAST_TO_RAW(EVENT_PAYLOAD);
ALTER TABLE PEN_REQUEST_BATCH_EVENT DROP COLUMN EVENT_PAYLOAD;
ALTER TABLE PEN_REQUEST_BATCH_EVENT RENAME COLUMN EVENT_PAYLOAD_BLOB TO EVENT_PAYLOAD;
ALTER TABLE PEN_REQUEST_BATCH_EVENT
    MODIFY (
        EVENT_PAYLOAD NOT NULL
        );
