CREATE TABLE PEN_REQUEST_BATCH_STUDENT_INFO_REQUEST_MACRO
(
    PRB_STUDENT_INFO_REQUEST_MACRO_ID   RAW(16)                 NOT NULL,
    MACRO_CODE                          VARCHAR2(4)             NOT NULL,
    MACRO_TEXT                          VARCHAR2(4000)          NOT NULL,
    CREATE_USER                         VARCHAR2(32)            NOT NULL,
    CREATE_DATE                         DATE   DEFAULT SYSDATE  NOT NULL,
    UPDATE_USER                         VARCHAR2(32)            NOT NULL,
    UPDATE_DATE                         DATE   DEFAULT SYSDATE  NOT NULL,
    CONSTRAINT PEN_REQUEST_BATCH_STUDENT_INFO_REQUEST_MACRO_PK PRIMARY KEY (PRB_STUDENT_INFO_REQUEST_MACRO_ID)
);

COMMENT ON TABLE PEN_REQUEST_BATCH_STUDENT_INFO_REQUEST_MACRO IS 'Holds macro codes and corresponding text for staff use to request more info from schools about PEN Requests.';
COMMENT ON COLUMN PEN_REQUEST_BATCH_STUDENT_INFO_REQUEST_MACRO.PRB_STUDENT_INFO_REQUEST_MACRO_ID IS 'Unique surrogate key for each macro.';
COMMENT ON COLUMN PEN_REQUEST_BATCH_STUDENT_INFO_REQUEST_MACRO.MACRO_CODE IS 'A short text code that identifies the macro and when identified will be replaced by the macro text.';
COMMENT ON COLUMN PEN_REQUEST_BATCH_STUDENT_INFO_REQUEST_MACRO.MACRO_TEXT IS 'A standard text string that will be substituted for the macro code by the application.';

INSERT INTO PEN_REQUEST_BATCH_STUDENT_INFO_REQUEST_MACRO (PRB_STUDENT_INFO_REQUEST_MACRO_ID, MACRO_CODE, MACRO_TEXT, CREATE_USER, CREATE_DATE, UPDATE_USER, UPDATE_DATE) VALUES (sys_guid(), 'BN', 'Surname and given name appear to be entered backwards, If correct, please confirm by sending legal documents.', 'IDIR/JOCOX', to_date('2020-10-15 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), 'IDIR/JOCOX', to_date('2020-10-15 00:00:00', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO PEN_REQUEST_BATCH_STUDENT_INFO_REQUEST_MACRO (PRB_STUDENT_INFO_REQUEST_MACRO_ID, MACRO_CODE, MACRO_TEXT, CREATE_USER, CREATE_DATE, UPDATE_USER, UPDATE_DATE) VALUES (sys_guid(), 'BTO', 'Unable to assign PEN, student appears to be to old.  If correct, please confirm by sending legal documents.', 'IDIR/JOCOX', to_date('2020-10-15 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), 'IDIR/JOCOX', to_date('2020-10-15 00:00:00', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO PEN_REQUEST_BATCH_STUDENT_INFO_REQUEST_MACRO (PRB_STUDENT_INFO_REQUEST_MACRO_ID, MACRO_CODE, MACRO_TEXT, CREATE_USER, CREATE_DATE, UPDATE_USER, UPDATE_DATE) VALUES (sys_guid(), 'BTY', 'Unable to assign PEN, birthdate too young for type of institution.', 'IDIR/JOCOX', to_date('2020-10-15 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), 'IDIR/JOCOX', to_date('2020-10-15 00:00:00', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO PEN_REQUEST_BATCH_STUDENT_INFO_REQUEST_MACRO (PRB_STUDENT_INFO_REQUEST_MACRO_ID, MACRO_CODE, MACRO_TEXT, CREATE_USER, CREATE_DATE, UPDATE_USER, UPDATE_DATE) VALUES (sys_guid(), 'CB', 'Please confirm the students birthdate with legal documentation and get back to us with the outcome.', 'IDIR/JOCOX', to_date('2020-10-15 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), 'IDIR/JOCOX', to_date('2020-10-15 00:00:00', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO PEN_REQUEST_BATCH_STUDENT_INFO_REQUEST_MACRO (PRB_STUDENT_INFO_REQUEST_MACRO_ID, MACRO_CODE, MACRO_TEXT, CREATE_USER, CREATE_DATE, UPDATE_USER, UPDATE_DATE) VALUES (sys_guid(), 'DF', 'This student appears to have a default birthdate entered.  If correct, please confirm by sending legal document.', 'IDIR/JOCOX', to_date('2020-10-15 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), 'IDIR/JOCOX', to_date('2020-10-15 00:00:00', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO PEN_REQUEST_BATCH_STUDENT_INFO_REQUEST_MACRO (PRB_STUDENT_INFO_REQUEST_MACRO_ID, MACRO_CODE, MACRO_TEXT, CREATE_USER, CREATE_DATE, UPDATE_USER, UPDATE_DATE) VALUES (sys_guid(), 'DFN', 'First name is duplicated in middle name.  Please remove and resubmit.  If student does not have a legal middle name, please leave the field blank.', 'IDIR/JOCOX', to_date('2020-10-15 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), 'IDIR/JOCOX', to_date('2020-10-15 00:00:00', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO PEN_REQUEST_BATCH_STUDENT_INFO_REQUEST_MACRO (PRB_STUDENT_INFO_REQUEST_MACRO_ID, MACRO_CODE, MACRO_TEXT, CREATE_USER, CREATE_DATE, UPDATE_USER, UPDATE_DATE) VALUES (sys_guid(), 'DFS', 'Student appears to have the first name duplicated in surname field. Please correct and resubmit or supply legal documentation to the ministry.', 'IDIR/JOCOX', to_date('2020-10-15 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), 'IDIR/JOCOX', to_date('2020-10-15 00:00:00', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO PEN_REQUEST_BATCH_STUDENT_INFO_REQUEST_MACRO (PRB_STUDENT_INFO_REQUEST_MACRO_ID, MACRO_CODE, MACRO_TEXT, CREATE_USER, CREATE_DATE, UPDATE_USER, UPDATE_DATE) VALUES (sys_guid(), 'DLN', 'Student appears to have the same Surname and Middle Name.  Please confirm the information and re-submit.', 'IDIR/JOCOX', to_date('2020-10-15 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), 'IDIR/JOCOX', to_date('2020-10-15 00:00:00', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO PEN_REQUEST_BATCH_STUDENT_INFO_REQUEST_MACRO (PRB_STUDENT_INFO_REQUEST_MACRO_ID, MACRO_CODE, MACRO_TEXT, CREATE_USER, CREATE_DATE, UPDATE_USER, UPDATE_DATE) VALUES (sys_guid(), 'DR', 'This record appears in the file more then once', 'IDIR/JOCOX', to_date('2020-10-15 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), 'IDIR/JOCOX', to_date('2020-10-15 00:00:00', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO PEN_REQUEST_BATCH_STUDENT_INFO_REQUEST_MACRO (PRB_STUDENT_INFO_REQUEST_MACRO_ID, MACRO_CODE, MACRO_TEXT, CREATE_USER, CREATE_DATE, UPDATE_USER, UPDATE_DATE) VALUES (sys_guid(), 'DS', 'Student in this file more then once.', 'IDIR/JOCOX', to_date('2020-10-15 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), 'IDIR/JOCOX', to_date('2020-10-15 00:00:00', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO PEN_REQUEST_BATCH_STUDENT_INFO_REQUEST_MACRO (PRB_STUDENT_INFO_REQUEST_MACRO_ID, MACRO_CODE, MACRO_TEXT, CREATE_USER, CREATE_DATE, UPDATE_USER, UPDATE_DATE) VALUES (sys_guid(), 'DSN', 'This student appears to be in the system with a different surname. Please contact the ministry to confirm.', 'IDIR/JOCOX', to_date('2020-10-15 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), 'IDIR/JOCOX', to_date('2020-10-15 00:00:00', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO PEN_REQUEST_BATCH_STUDENT_INFO_REQUEST_MACRO (PRB_STUDENT_INFO_REQUEST_MACRO_ID, MACRO_CODE, MACRO_TEXT, CREATE_USER, CREATE_DATE, UPDATE_USER, UPDATE_DATE) VALUES (sys_guid(), 'IC', 'Unable to assign PEN, invalid code or characters in record.  Please remove and resubmit.', 'IDIR/JOCOX', to_date('2020-10-15 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), 'IDIR/JOCOX', to_date('2020-10-15 00:00:00', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO PEN_REQUEST_BATCH_STUDENT_INFO_REQUEST_MACRO (PRB_STUDENT_INFO_REQUEST_MACRO_ID, MACRO_CODE, MACRO_TEXT, CREATE_USER, CREATE_DATE, UPDATE_USER, UPDATE_DATE) VALUES (sys_guid(), 'ILN', 'Invalid Surname', 'IDIR/JOCOX', to_date('2020-10-15 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), 'IDIR/JOCOX', to_date('2020-10-15 00:00:00', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO PEN_REQUEST_BATCH_STUDENT_INFO_REQUEST_MACRO (PRB_STUDENT_INFO_REQUEST_MACRO_ID, MACRO_CODE, MACRO_TEXT, CREATE_USER, CREATE_DATE, UPDATE_USER, UPDATE_DATE) VALUES (sys_guid(), 'IN', 'You have entered an invalid name in one of the fields.  Please re-submit.', 'IDIR/JOCOX', to_date('2020-10-15 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), 'IDIR/JOCOX', to_date('2020-10-15 00:00:00', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO PEN_REQUEST_BATCH_STUDENT_INFO_REQUEST_MACRO (PRB_STUDENT_INFO_REQUEST_MACRO_ID, MACRO_CODE, MACRO_TEXT, CREATE_USER, CREATE_DATE, UPDATE_USER, UPDATE_DATE) VALUES (sys_guid(), 'INF', 'Invalid name formatting. Please fix and resubmit.', 'IDIR/JOCOX', to_date('2020-10-15 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), 'IDIR/JOCOX', to_date('2020-10-15 00:00:00', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO PEN_REQUEST_BATCH_STUDENT_INFO_REQUEST_MACRO (PRB_STUDENT_INFO_REQUEST_MACRO_ID, MACRO_CODE, MACRO_TEXT, CREATE_USER, CREATE_DATE, UPDATE_USER, UPDATE_DATE) VALUES (sys_guid(), 'LEG', 'This record does not appear to be entered in your system using legal documentation, please correct your system and resubmit to the ministry to PEN.', 'IDIR/JOCOX', to_date('2020-10-15 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), 'IDIR/JOCOX', to_date('2020-10-15 00:00:00', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO PEN_REQUEST_BATCH_STUDENT_INFO_REQUEST_MACRO (PRB_STUDENT_INFO_REQUEST_MACRO_ID, MACRO_CODE, MACRO_TEXT, CREATE_USER, CREATE_DATE, UPDATE_USER, UPDATE_DATE) VALUES (sys_guid(), 'LNF', 'Unable to assign PEN student correct demographics using legal document and resubmit record to the ministry. If correct contact Pens.coordinator@gov.bc.ca', 'IDIR/JOCOX', to_date('2020-10-15 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), 'IDIR/JOCOX', to_date('2020-10-15 00:00:00', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO PEN_REQUEST_BATCH_STUDENT_INFO_REQUEST_MACRO (PRB_STUDENT_INFO_REQUEST_MACRO_ID, MACRO_CODE, MACRO_TEXT, CREATE_USER, CREATE_DATE, UPDATE_USER, UPDATE_DATE) VALUES (sys_guid(), 'MAN', 'Legal name appears to be missing or incomplete. If correct, please confirm by sending legal document.', 'IDIR/JOCOX', to_date('2020-10-15 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), 'IDIR/JOCOX', to_date('2020-10-15 00:00:00', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO PEN_REQUEST_BATCH_STUDENT_INFO_REQUEST_MACRO (PRB_STUDENT_INFO_REQUEST_MACRO_ID, MACRO_CODE, MACRO_TEXT, CREATE_USER, CREATE_DATE, UPDATE_USER, UPDATE_DATE) VALUES (sys_guid(), 'MB', 'Unable to assign PEN, missing or invalid birthdate. Please correct and resubmit.', 'IDIR/JOCOX', to_date('2020-10-15 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), 'IDIR/JOCOX', to_date('2020-10-15 00:00:00', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO PEN_REQUEST_BATCH_STUDENT_INFO_REQUEST_MACRO (PRB_STUDENT_INFO_REQUEST_MACRO_ID, MACRO_CODE, MACRO_TEXT, CREATE_USER, CREATE_DATE, UPDATE_USER, UPDATE_DATE) VALUES (sys_guid(), 'MDN', 'Possible match found, please contact pens.coordinator@gov.bc.ca with students maiden name or any previously used name.', 'IDIR/JOCOX', to_date('2020-10-15 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), 'IDIR/JOCOX', to_date('2020-10-15 00:00:00', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO PEN_REQUEST_BATCH_STUDENT_INFO_REQUEST_MACRO (PRB_STUDENT_INFO_REQUEST_MACRO_ID, MACRO_CODE, MACRO_TEXT, CREATE_USER, CREATE_DATE, UPDATE_USER, UPDATE_DATE) VALUES (sys_guid(), 'MFN', 'Unable to assign PEN, missing or invalid first name.  Please correct and resubmit. If correct, please confirm by sending legal document.', 'IDIR/JOCOX', to_date('2020-10-15 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), 'IDIR/JOCOX', to_date('2020-10-15 00:00:00', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO PEN_REQUEST_BATCH_STUDENT_INFO_REQUEST_MACRO (PRB_STUDENT_INFO_REQUEST_MACRO_ID, MACRO_CODE, MACRO_TEXT, CREATE_USER, CREATE_DATE, UPDATE_USER, UPDATE_DATE) VALUES (sys_guid(), 'MG', 'Unable to assign PEN, missing or invalid gender.  Please correct and resubmit.', 'IDIR/JOCOX', to_date('2020-10-15 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), 'IDIR/JOCOX', to_date('2020-10-15 00:00:00', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO PEN_REQUEST_BATCH_STUDENT_INFO_REQUEST_MACRO (PRB_STUDENT_INFO_REQUEST_MACRO_ID, MACRO_CODE, MACRO_TEXT, CREATE_USER, CREATE_DATE, UPDATE_USER, UPDATE_DATE) VALUES (sys_guid(), 'MGB', 'Unable to assign PEN, missing or invalid birthdate and gender.  Please correct and resubmit.', 'IDIR/JOCOX', to_date('2020-10-15 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), 'IDIR/JOCOX', to_date('2020-10-15 00:00:00', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO PEN_REQUEST_BATCH_STUDENT_INFO_REQUEST_MACRO (PRB_STUDENT_INFO_REQUEST_MACRO_ID, MACRO_CODE, MACRO_TEXT, CREATE_USER, CREATE_DATE, UPDATE_USER, UPDATE_DATE) VALUES (sys_guid(), 'MLN', 'Unable to assign PEN, missing or invalid surname.  Please correct and resubmit. If correct, please confirm by sending legal document.', 'IDIR/JOCOX', to_date('2020-10-15 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), 'IDIR/JOCOX', to_date('2020-10-15 00:00:00', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO PEN_REQUEST_BATCH_STUDENT_INFO_REQUEST_MACRO (PRB_STUDENT_INFO_REQUEST_MACRO_ID, MACRO_CODE, MACRO_TEXT, CREATE_USER, CREATE_DATE, UPDATE_USER, UPDATE_DATE) VALUES (sys_guid(), 'MMN', 'Possible match found, please supply missing middle name to confirm match. If student has no legal middle name, please confirm by sending legal document.', 'IDIR/JOCOX', to_date('2020-10-15 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), 'IDIR/JOCOX', to_date('2020-10-15 00:00:00', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO PEN_REQUEST_BATCH_STUDENT_INFO_REQUEST_MACRO (PRB_STUDENT_INFO_REQUEST_MACRO_ID, MACRO_CODE, MACRO_TEXT, CREATE_USER, CREATE_DATE, UPDATE_USER, UPDATE_DATE) VALUES (sys_guid(), 'MP', 'Possible match found, please supply postal code to confirm match.', 'IDIR/JOCOX', to_date('2020-10-15 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), 'IDIR/JOCOX', to_date('2020-10-15 00:00:00', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO PEN_REQUEST_BATCH_STUDENT_INFO_REQUEST_MACRO (PRB_STUDENT_INFO_REQUEST_MACRO_ID, MACRO_CODE, MACRO_TEXT, CREATE_USER, CREATE_DATE, UPDATE_USER, UPDATE_DATE) VALUES (sys_guid(), 'MSD', 'There appears to be two different students entered in this record, please confirm the legal and usual names in your student admin system and resubmit.', 'IDIR/JOCOX', to_date('2020-10-15 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), 'IDIR/JOCOX', to_date('2020-10-15 00:00:00', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO PEN_REQUEST_BATCH_STUDENT_INFO_REQUEST_MACRO (PRB_STUDENT_INFO_REQUEST_MACRO_ID, MACRO_CODE, MACRO_TEXT, CREATE_USER, CREATE_DATE, UPDATE_USER, UPDATE_DATE) VALUES (sys_guid(), 'NAN', 'Please provide the legal Asian name or legal documentation for this student.  There are several identical matches in our system.', 'IDIR/JOCOX', to_date('2020-10-15 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), 'IDIR/JOCOX', to_date('2020-10-15 00:00:00', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO PEN_REQUEST_BATCH_STUDENT_INFO_REQUEST_MACRO (PRB_STUDENT_INFO_REQUEST_MACRO_ID, MACRO_CODE, MACRO_TEXT, CREATE_USER, CREATE_DATE, UPDATE_USER, UPDATE_DATE) VALUES (sys_guid(), 'PCB', 'Possible match found, please confirm birthdate.  If correct, please confirm by sending legal document.', 'IDIR/JOCOX', to_date('2020-10-15 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), 'IDIR/JOCOX', to_date('2020-10-15 00:00:00', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO PEN_REQUEST_BATCH_STUDENT_INFO_REQUEST_MACRO (PRB_STUDENT_INFO_REQUEST_MACRO_ID, MACRO_CODE, MACRO_TEXT, CREATE_USER, CREATE_DATE, UPDATE_USER, UPDATE_DATE) VALUES (sys_guid(), 'PCG', 'Possible match found, please confirm gender. If correct, please confirm by sending legal document.', 'IDIR/JOCOX', to_date('2020-10-15 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), 'IDIR/JOCOX', to_date('2020-10-15 00:00:00', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO PEN_REQUEST_BATCH_STUDENT_INFO_REQUEST_MACRO (PRB_STUDENT_INFO_REQUEST_MACRO_ID, MACRO_CODE, MACRO_TEXT, CREATE_USER, CREATE_DATE, UPDATE_USER, UPDATE_DATE) VALUES (sys_guid(), 'PCN', 'Possible match found, please confirm legal name. If correct, please confirm by sending legal document.', 'IDIR/JOCOX', to_date('2020-10-15 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), 'IDIR/JOCOX', to_date('2020-10-15 00:00:00', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO PEN_REQUEST_BATCH_STUDENT_INFO_REQUEST_MACRO (PRB_STUDENT_INFO_REQUEST_MACRO_ID, MACRO_CODE, MACRO_TEXT, CREATE_USER, CREATE_DATE, UPDATE_USER, UPDATE_DATE) VALUES (sys_guid(), 'SIB', 'This student is already in BCeSIS. Please do a restricted query to find the student and admit them to your school. Contact your BCeSIS Lvl 1 for assistance.', 'IDIR/JOCOX', to_date('2020-10-15 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), 'IDIR/JOCOX', to_date('2020-10-15 00:00:00', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO PEN_REQUEST_BATCH_STUDENT_INFO_REQUEST_MACRO (PRB_STUDENT_INFO_REQUEST_MACRO_ID, MACRO_CODE, MACRO_TEXT, CREATE_USER, CREATE_DATE, UPDATE_USER, UPDATE_DATE) VALUES (sys_guid(), 'SIS', 'There are two records in BCeSIS for this student.  Contact your BCeSIS L1 support for help in finding the duplicate and deleting the incorrect record.', 'IDIR/JOCOX', to_date('2020-10-15 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), 'IDIR/JOCOX', to_date('2020-10-15 00:00:00', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO PEN_REQUEST_BATCH_STUDENT_INFO_REQUEST_MACRO (PRB_STUDENT_INFO_REQUEST_MACRO_ID, MACRO_CODE, MACRO_TEXT, CREATE_USER, CREATE_DATE, UPDATE_USER, UPDATE_DATE) VALUES (sys_guid(), 'TEST', 'This appears to be a test record, please delete from your system.', 'IDIR/JOCOX', to_date('2020-10-15 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), 'IDIR/JOCOX', to_date('2020-10-15 00:00:00', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO PEN_REQUEST_BATCH_STUDENT_INFO_REQUEST_MACRO (PRB_STUDENT_INFO_REQUEST_MACRO_ID, MACRO_CODE, MACRO_TEXT, CREATE_USER, CREATE_DATE, UPDATE_USER, UPDATE_DATE) VALUES (sys_guid(), 'TMFN', 'Too many names entered in first name field, please reformat and resubmit.', 'IDIR/JOCOX', to_date('2020-10-15 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), 'IDIR/JOCOX', to_date('2020-10-15 00:00:00', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO PEN_REQUEST_BATCH_STUDENT_INFO_REQUEST_MACRO (PRB_STUDENT_INFO_REQUEST_MACRO_ID, MACRO_CODE, MACRO_TEXT, CREATE_USER, CREATE_DATE, UPDATE_USER, UPDATE_DATE) VALUES (sys_guid(), 'TMUN', 'Too many names enterd in the usual name field.  This field should only contain names that the student wants to be called by.  Legal names should not appear.', 'IDIR/JOCOX', to_date('2020-10-15 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), 'IDIR/JOCOX', to_date('2020-10-15 00:00:00', 'YYYY-MM-DD HH24:MI:SS'));
