CREATE TABLE STUDENT_EVENT
(
    EVENT_ID      RAW(16)                             NOT NULL,
    EVENT_PAYLOAD VARCHAR2(4000)                       NOT NULL,
    EVENT_STATUS  VARCHAR2(50)                        NOT NULL,
    EVENT_TYPE    VARCHAR2(100)                       NOT NULL,
    SAGA_ID       RAW(16),
    EVENT_OUTCOME VARCHAR2(100)                       NOT NULL,
    REPLY_CHANNEL VARCHAR2(100),
    CREATE_USER   VARCHAR(32)                         NOT NULL,
    CREATE_DATE   TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    UPDATE_USER   VARCHAR(32)                         NOT NULL,
    UPDATE_DATE   TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT STUDENT_EVENT_PK PRIMARY KEY (EVENT_ID)
);
CREATE INDEX STUDENT_EVENT_EVENT_STATUS_IDX ON STUDENT_EVENT (EVENT_STATUS) TABLESPACE API_STUDENT_IDX;
CREATE INDEX STUDENT_EVENT_SAGA_ID_IDX ON STUDENT_EVENT (SAGA_ID) TABLESPACE API_STUDENT_IDX;
CREATE INDEX STUDENT_EVENT_EVENT_TYPE_IDX ON STUDENT_EVENT (EVENT_TYPE) TABLESPACE API_STUDENT_IDX;


CREATE TABLE STUDENT_SHEDLOCK
(
    NAME       VARCHAR(64),
    LOCK_UNTIL TIMESTAMP(3) NULL,
    LOCKED_AT  TIMESTAMP(3) NULL,
    LOCKED_BY  VARCHAR(255),
    CONSTRAINT STUDENT_SHEDLOCK_PK PRIMARY KEY (NAME)
);
COMMENT ON TABLE STUDENT_SHEDLOCK IS 'This table is used to achieve distributed lock between pods, for schedulers.';