DROP TABLE PEN_REQUEST_BATCH_HISTORY;

ALTER TABLE PEN_REQUEST_BATCH
ADD (
    PEN_REQUEST_BATCH_PROCESS_TYPE_CODE     VARCHAR2(10)  NOT NULL
);

COMMENT ON COLUMN PEN_REQUEST_BATCH.PEN_REQUEST_BATCH_PROCESS_TYPE_CODE IS 'The batch processing type used (API or FLATFILE).';

--PEN Request Batch History
CREATE TABLE PEN_REQUEST_BATCH_HISTORY
(
    PEN_REQUEST_BATCH_HISTORY_ID  RAW(16) NOT NULL,
    PEN_REQUEST_BATCH_ID            RAW(16)       NOT NULL,
    EVENT_DATE                    DATE                 NOT NULL,
    PEN_REQUEST_BATCH_EVENT_CODE  VARCHAR2(10) NOT NULL,
    EVENT_REASON                  VARCHAR2(255),
    SUBMISSION_NO                   VARCHAR2(8)   NOT NULL,
    PEN_REQUEST_BATCH_STATUS_CODE   VARCHAR2(10)  NOT NULL,
    PEN_REQUEST_BATCH_STATUS_REASON VARCHAR2(255),
    PEN_REQUEST_BATCH_TYPE_CODE     VARCHAR2(10)  NOT NULL,
    FILE_NAME                       VARCHAR2(255) NOT NULL,
    FILE_TYPE                       VARCHAR2(4)   NOT NULL,
    INSERT_DATE                     DATE          NOT NULL,
    EXTRACT_DATE                    DATE          NOT NULL,
    PROCESS_DATE                    DATE,
    SOURCE_APPLICATION              VARCHAR2(6)   NOT NULL,
    MINISTRY_PRB_SOURCE_CODE        VARCHAR2(10)  NOT NULL,
    MINCODE                         VARCHAR2(8),
    SCHOOL_NAME                     VARCHAR2(255),
    CONTACT_NAME                    VARCHAR2(255),
    EMAIL                           VARCHAR2(255),
    OFFICE_NUMBER                   NUMBER,
    SOURCE_STUDENT_COUNT            NUMBER,
    STUDENT_COUNT                   NUMBER,
    BATCH_TYPE
    SIS_VENDOR_NAME                 VARCHAR2(100),
    SIS_PRODUCT_NAME                VARCHAR2(100),
    SIS_PRODUCT_ID                  VARCHAR2(15),
    MATCHED_COUNT                   NUMBER,
    NEW_PEN_COUNT                   NUMBER,
    ERROR_COUNT                     NUMBER,
    REPEAT_COUNT                    NUMBER,
    FIXABLE_COUNT                   NUMBER,
    SCHOOL_GROUP_CODE               VARCHAR2(10),
    PEN_REQUEST_BATCH_PROCESS_TYPE_CODE     VARCHAR2(10)  NOT NULL,
    CREATE_USER                   VARCHAR2(32) NOT NULL,
    CREATE_DATE                   DATE DEFAULT SYSDATE NOT NULL,
    UPDATE_USER                   VARCHAR2(32) NOT NULL,
    UPDATE_DATE                   DATE DEFAULT SYSDATE NOT NULL,

    CONSTRAINT PEN_REQUEST_BATCH_HISTORY_PK PRIMARY KEY (PEN_REQUEST_BATCH_HISTORY_ID)
);
COMMENT
ON TABLE PEN_REQUEST_BATCH_HISTORY IS 'Contains Each change the PEN REQUEST BATCH Table goes through.';

COMMENT ON COLUMN PEN_REQUEST_BATCH_HISTORY.EVENT_DATE IS 'Date and time at which the PEN Request Batch event occurred.';
COMMENT ON COLUMN PEN_REQUEST_BATCH_HISTORY.PEN_REQUEST_BATCH_EVENT_CODE IS 'Code identifying the type of event that occurred with the batch. Examples: Status Change, Responses returned to school.';
COMMENT ON COLUMN PEN_REQUEST_BATCH_HISTORY.PEN_REQUEST_BATCH_STATUS_CODE IS 'Code identifying the status of the batch after the event. This is provided for all event types, not just status changes. For status changes, it is the new value of the status, as a result of the change.';
COMMENT ON COLUMN PEN_REQUEST_BATCH_HISTORY.EVENT_REASON IS 'Additional information about the event, that is recorded only when needed.';
COMMENT ON COLUMN PEN_REQUEST_BATCH_HISTORY.PEN_REQUEST_BATCH_HISTORY_ID IS 'Unique surrogate key for each PEN Request Batch History record. GUID value must be provided during insert.';
COMMENT ON COLUMN PEN_REQUEST_BATCH_HISTORY.PEN_REQUEST_BATCH_ID IS 'Foreign key to the parent PEN Request Batch record.';
COMMENT ON COLUMN PEN_REQUEST_BATCH_HISTORY.SUBMISSION_NO IS 'Unique natural identifier for each PEN Request Batch. At present (2020), these are generated by TSW as these files are added to the TSW.PEN_WEB_BLOBS table.';
COMMENT ON COLUMN PEN_REQUEST_BATCH_HISTORY.PEN_REQUEST_BATCH_STATUS_CODE IS 'A code identifying the current status of the batch.';
COMMENT ON COLUMN PEN_REQUEST_BATCH_HISTORY.PEN_REQUEST_BATCH_STATUS_REASON IS 'Reason for the current batch status. Only specified during exceptional circumstances.';
COMMENT ON COLUMN PEN_REQUEST_BATCH_HISTORY.FILE_NAME IS 'The name of the batch file uploaded by the school. Should be "<mincode>.PEN" ';
COMMENT ON COLUMN PEN_REQUEST_BATCH_HISTORY.FILE_TYPE IS 'The type of the file uploaded by the school.';
COMMENT ON COLUMN PEN_REQUEST_BATCH_HISTORY.INSERT_DATE IS 'The date and time the file landed at the Ministry of Education.';
COMMENT ON COLUMN PEN_REQUEST_BATCH_HISTORY.EXTRACT_DATE IS 'The date the file was extracted and loaded.';
COMMENT ON COLUMN PEN_REQUEST_BATCH_HISTORY.PROCESS_DATE IS 'The date the file was processed.';
COMMENT ON COLUMN PEN_REQUEST_BATCH_HISTORY.SOURCE_APPLICATION IS 'A short code identifying the source system at the school. This is defined by the schools and is not constrained by a code table. ';
COMMENT ON COLUMN PEN_REQUEST_BATCH_HISTORY.MINISTRY_PRB_SOURCE_CODE IS 'A code identifying which ministry system received the file, such as TSW PENWeb. Default "TSWPENWEB"';
COMMENT ON COLUMN PEN_REQUEST_BATCH_HISTORY.MINCODE IS 'Ministry code for the school that submitted the batch.';
COMMENT ON COLUMN PEN_REQUEST_BATCH_HISTORY.SCHOOL_NAME IS 'Name of the school as provided in the batch file.';
COMMENT ON COLUMN PEN_REQUEST_BATCH_HISTORY.CONTACT_NAME IS 'Name of the contact person for the school.';
COMMENT ON COLUMN PEN_REQUEST_BATCH_HISTORY.EMAIL IS 'Email for the contact person.';
COMMENT ON COLUMN PEN_REQUEST_BATCH_HISTORY.OFFICE_NUMBER IS 'Identifies which school office submitted the request. Only use by schools with multiple offices.';
COMMENT ON COLUMN PEN_REQUEST_BATCH_HISTORY.SOURCE_STUDENT_COUNT IS 'The number of students contained in the batch, according to the data in the source system.';
COMMENT ON COLUMN PEN_REQUEST_BATCH_HISTORY.STUDENT_COUNT IS 'The number of students contained in the batch.';
COMMENT ON COLUMN PEN_REQUEST_BATCH_HISTORY.PEN_REQUEST_BATCH_TYPE_CODE IS ' A code identifying the type the batch: Normal School batch, Nominal Roll batch, SLD Validation batch.';
COMMENT ON COLUMN PEN_REQUEST_BATCH_HISTORY.SIS_VENDOR_NAME IS 'The name of the vendor of the Student information System (SIS) used by the submitting school. E.g. Follett';
COMMENT ON COLUMN PEN_REQUEST_BATCH_HISTORY.SIS_PRODUCT_NAME IS 'The name of the Student information System (SIS) product used by the submitting school. E.g. Aspen';
COMMENT ON COLUMN PEN_REQUEST_BATCH_HISTORY.SIS_PRODUCT_ID IS 'The ID of the Student information System (SIS) product used by the submitting school. E.g. A version number.';
COMMENT ON COLUMN PEN_REQUEST_BATCH_HISTORY.MATCHED_COUNT IS 'A dynamic, running count of the number of PEN request records in the batch that have been matched to existing records in the Student table.';
COMMENT ON COLUMN PEN_REQUEST_BATCH_HISTORY.ISSUED_PEN_COUNT IS 'A dynamic, running count of the number of PEN request records in the batch that resulted in the creation of a new Student/PEN in the Student table.';
COMMENT ON COLUMN PEN_REQUEST_BATCH_HISTORY.ERROR_COUNT IS 'A dynamic, running count of the number of PEN request records in the batch that have errors of some sort (PEN not yet matched nor issued). Includes Validation errors, Repeats and Fixables.';
COMMENT ON COLUMN PEN_REQUEST_BATCH_HISTORY.REPEAT_COUNT IS 'A dynamic, running count of the number of PEN request records in the batch that are a repeat of an earlier PEN request by the same school, using the same request data.';
COMMENT ON COLUMN PEN_REQUEST_BATCH_HISTORY.FIXABLE_COUNT IS 'A dynamic, running count of the number of PEN request records in the batch that are valid requests but could not automatically be fulfilled, and require manual review.';
COMMENT ON COLUMN PEN_REQUEST_BATCH_HISTORY.PEN_REQUEST_BATCH_PROCESS_TYPE_CODE IS 'The batch processing type used (API or FLATFILE).';

ALTER TABLE PEN_REQUEST_BATCH_HISTORY
    ADD CONSTRAINT PEN_REQUEST_BATCH_HISTORY_PEN_REQUEST_BATCH_ID_FK FOREIGN KEY (PEN_REQUEST_BATCH_ID) REFERENCES PEN_REQUEST_BATCH (PEN_REQUEST_BATCH_ID);
ALTER TABLE PEN_REQUEST_BATCH_HISTORY
    ADD CONSTRAINT PEN_REQUEST_BATCH_HISTORY_PEN_REQUEST_BATCH_EVENT_CODE_FK FOREIGN KEY (PEN_REQUEST_BATCH_EVENT_CODE) REFERENCES PEN_REQUEST_BATCH_EVENT_CODE (PEN_REQUEST_BATCH_EVENT_CODE);
ALTER TABLE PEN_REQUEST_BATCH_HISTORY
    ADD CONSTRAINT PEN_REQUEST_BATCH_HISTORY_PEN_REQUEST_BATCH_STATUS_CODE_FK FOREIGN KEY (PEN_REQUEST_BATCH_STATUS_CODE) REFERENCES PEN_REQUEST_BATCH_STATUS_CODE (PEN_REQUEST_BATCH_STATUS_CODE);