---
apiVersion: template.openshift.io/v1
kind: Template
labels:
  template: 'pen-reg-batch-api-template'
metadata:
  name: 'pen-reg-batch-api-template'
objects:
  - apiVersion: v1
    kind: BuildConfig
    metadata:
      labels:
        build: pen-reg-batch-api-pipeline
      name: pen-reg-batch-api-pipeline
    spec:
      source:
        git:
          ref: master
          uri: 'https://github.com/bcgov/EDUC-PEN-REG-BATCH-API'
        type: Git
      strategy:
        jenkinsPipelineStrategy:
          jenkinsfilePath: tools/jenkins/Jenkinsfile-api
