name: API CI

on:
  workflow_dispatch:  
  push:
    branches:
      - master
      - 'feature/**'
      - 'Feature/**'
      - 'fix/*'
      - 'Fix/*'
    paths:
      - 'api/**'
  pull_request:
    branches: [ master ]
    paths:
      - 'api/**'
jobs:
  quality_profile:

    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: api

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-java@v1
        with:
          java-version: 11
      - uses: actions/cache@v1
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: Run unit tests
        run: mvn -f pom.xml clean test
      - name: Cache SonarCloud packages
        uses: actions/cache@v1
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
      - name: Run Sonar Analysis
        run: mvn -f pom.xml sonar:sonar
          -Dsonar.login=${{ secrets.SONAR_TOKEN }}
          -Dsonar.host.url=https://sonarcloud.io
          -Dsonar.organization=bcgov-sonarcloud
          -Dsonar.projectKey=${{ secrets.SONAR_PROJECT_KEY }}
        env:
          GITHUB_TOKEN: ${{ github.token }}
      - name: Run Trivy vulnerability scanner in repo mode
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'fs'
          ignore-unfixed: true
          format: 'template'
          template: '@/contrib/sarif.tpl'
          output: 'trivy-results.sarif'
          severity: 'LOW'

      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v1
        with:
          sarif_file: 'trivy-results.sarif'
